frameworkVersion: '>=1.21.0 <2.0.0'
service: '${self:provider.environment.SERVICE}'

# Custom variables
# ===================================================================
custom:
  stage: '${opt:stage, self:provider.stage}'
  # domain: "api.metricjam.com"
  documentation:
    version: '1'
    summary: 'My API'
    description: 'This is my API'
    tags:
      -
        name: 'greeting'
        description: 'Services to display greetings'

# The `provider` block defines where your service will be deployed
# ===================================================================
provider:
  name: aws
  stage: dev
  runtime: nodejs6.10
  environment: ${file(./serverless.env.yml):${self:custom.stage}}
  region: ${self:provider.environment.REGION}
  profile: ${self:provider.environment.PROFILE}
  timeout: 30
  memorySize: 128
  versionFunctions: true

# The `Functions` you want to deploy
# ===================================================================
functions:
  auth:
    handler: src/handlers/handler.auth
  tokenEndpoint:
    handler: src/handlers/handler.tokenEndpoint
    events:
      - http:
          path: api/token
          method: get
          integration: lambda
          cors: true
  publicEndpoint:
    handler: src/handlers/handler.publicEndpoint
    events:
      - http:
          path: api/public
          method: get
          integration: lambda
          cors: true
  privateEndpoint:
    handler: src/handlers/handler.privateEndpoint
    events:
      - http:
          path: api/private
          method: post
          integration: lambda
          authorizer: auth # See custom authorizer docs here: http://bit.ly/2gXw9pO
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
              - Access-Control-Expose-Headers
  # Hello
  # -------------------------------------------------------
  hello:
    handler: src/handlers/user.greeting
    events:
      - http:
          path: hello
          method: get
          documentation:
            summary: "Greetings"
            description: "Display a random greeting"

plugins:
  - serverless-plugin-typescript
  - serverless-aws-documentation
  - serverless-enable-api-logs
  - serverless-plugin-custom-domain
  - serverless-offline

package:
  exclude:
    - package.json
    - .git
  include:
    - src
    - node_modules/**/*
